package com.example.ratesapp.rates

// TODO moce?
object CurrencyIds {
    const val ID_AUD = "AUD"
    const val ID_BGN = "BGN"
    const val ID_BRL = "BRL"
    const val ID_CAD = "CAD"
    const val ID_CHF = "CHF"
    const val ID_CNY = "CNY"
    const val ID_CZK = "CZK"
    const val ID_DKK = "DKK"
    const val ID_EUR = "EUR"
    const val ID_GBP = "GBP"
    const val ID_HKD = "HKD"
    const val ID_HRK = "HRK"
    const val ID_HUF = "HUF"
    const val ID_IDR = "IDR"
    const val ID_ILS = "ILS"
    const val ID_INR = "INR"
    const val ID_ISK = "ISK"
    const val ID_JPY = "JPY"
    const val ID_KRW = "KRW"
    const val ID_MXN = "MXN"
    const val ID_MYR = "MYR"
    const val ID_NOK = "NOK"
    const val ID_NZD = "NZD"
    const val ID_PHP = "PHP"
    const val ID_PLN = "PLN"
    const val ID_RON = "RON"
    const val ID_RUB = "RUB"
    const val ID_SEK = "SEK"
    const val ID_SGD = "SGD"
    const val ID_THB = "THB"
    const val ID_USD = "USD"
    const val ID_ZAR = "ZAR"
}